sudo: required
services:
  - docker 

before_install:
  - docker build -t drkwiz8/docker-react -f Dockerfile.dev .

script:
  - docker run drkwiz8/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: elasticbeanstalk-us-east-2-728857662096
  bucker_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"